version: '3'
services:
  wordpress_db:
    image: mariadb:latest
    volumes:
      - type: bind
        source: ${PCC_WEB_DATA}/wordpress_db
        target: /var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${PCC_WORDPRESS_DB_PASSWORD}
    restart: unless-stopped
    pull_policy: always
  wordpress:
    depends_on:
      - wordpress_db
    image: ghcr.io/pccsuite/pccweb/wordpress:latest
    volumes:
      - type: bind
        source: ${PCC_WEB_DATA}/html/wordpress
        target: /var/www/html/wordpress
    ports:
      - "8001:80"
    environment:
      WORDPRESS_DB_HOST: wordpress_db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${PCC_WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    restart: unless-stopped
    pull_policy: always
  wordpress_cli:
    depends_on:
      - wordpress_db
    image: wordpress:cli
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ${PCC_WEB_DATA}/html/wordpress
        target: /var/www/html/wordpress
    working_dir: "/var/www/html/wordpress"
    environment:
      WORDPRESS_DB_HOST: wordpress_db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${PCC_WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    pull_policy: always
    profiles:
      - wp-cli
  mediawiki_db:
    image: mariadb:latest
    volumes:
      - type: bind
        source: ${PCC_WEB_DATA}/mediawiki_db
        target: /var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: mediawiki
      MYSQL_USER: mediawiki
      MYSQL_PASSWORD: ${PCC_MEDIAWIKI_DB_PASSWORD}
    restart: unless-stopped
    pull_policy: always
  mediawiki:
    depends_on:
      - mediawiki_db
    image: ghcr.io/pccsuite/pccweb/mediawiki:latest
    volumes:
      - type: bind
        source: ${PCC_WEB_DATA}/html/mediawiki/images
        target: /var/www/html/mediawiki/images
      - type: bind
        source: ${PCC_WEB_DATA}/html/mediawiki/LocalSettings.php
        target: /var/www/html/mediawiki/LocalSettings.php
    ports:
      - "8002:80"
    restart: unless-stopped
    pull_policy: always
  attend:
    image: ghcr.io/pccsuite/pccattendancechecker-next
    ports:
      - "8008:3000"
    volumes:
      - type: bind
        source: ${PCC_WEB_DATA}/attend_db.sqlite
        target: /data/attend.sqlite
    restart: unless-stopped
    pull_policy: always
  caddy:
    image: caddy:alpine
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: caddy/Caddyfile
        target: /etc/caddy/Caddyfile
      - type: bind
        source: ${PCC_WEB_DATA}/html
        target: /var/www/html
    restart: unless-stopped
    pull_policy: always
