name: Mediawiki Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'mediawiki/**'

defaults:
  run:
    working-directory: mediawiki

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:mediawiki"
          push: true
          tags: ghcr.io/pccsuite/pccweb/mediawiki:latest
